# Generated by Django 4.2.1 on 2023-05-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdoc', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='content',
        ),
    ]
