# Generated by Django 4.2.1 on 2023-05-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdoc', '0003_remove_document_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(default='Template Content'),
            preserve_default=False,
        ),
    ]
